[workspace]
members = ["cli", "tests"]
default-members = ["cli"]

[workspace.package]
version = "0.4.1"
authors = ["Martin Haug <mhaug@live.de>"]
edition = "2021"
repository = "https://github.com/typst/svg2pdf"
readme = "README.md"
license = "MIT OR Apache-2.0"

[package]
name = "svg2pdf"
description = "Convert SVG files to PDFs."
categories = ["encoding", "graphics", "multimedia"]
keywords = ["svg", "pdf", "vector-graphics", "conversion"]
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
miniz_oxide = "0.7"
pdf-writer = "0.7"
usvg = "0.32"
image = "0.24"
nalgebra = "0.32.2"
