name: Continuous integration
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
#      - uses: actions/checkout@v3
#      - uses: dtolnay/rust-toolchain@stable
#      - uses: Swatinem/rust-cache@v2
#      - uses: actions/upload-artifact@v3
#        with:
#          path: references/resvg/shapes/circle/simple-case.png
      - run: ls .
#      - run: cargo build --package svg2pdf-tests --bin test --release
#      - run: cargo run --package svg2pdf-tests --bin test --release

#  checks:
#    name: Check clippy, formatting, and documentation
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: dtolnay/rust-toolchain@stable
#      - uses: Swatinem/rust-cache@v2
#      - run: cargo clippy --all-targets
#      - run: cargo fmt --check --all